# Build stage
FROM golang:1.25.5-alpine AS builder
WORKDIR /app

# Copy go.mod & go.sum và download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code và build
COPY . .
RUN go build -o /app/app

# Final stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app /app/app
EXPOSE 8080
CMD ["/app/app"]
